version: '2.0'
services:
  dcm-admin:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - /scor-data:/scor-data
    environments:
      DEBUG: True
      SQLALCHEMY_TRACK_MODIFICATIONS: False
      SQLALCHEMY_DATABASE_URI: sqlite:///urldebase      		
      SECRET_KEY: my_precious_secret_key
      DEBUG: False
      MONGO_URI: mongodb://dcm-consmos:pUQRAZMYnTiYikWTxjcq7zQch27litMHCSJnHOu9XCssYxBqVRWmMpd8sSnd0G7w66dQ7GMS4UK8iAvOsoBGtw==@dcm-consmos.mongo.cosmos.azure.com:10255/dcm?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dcm-consmos@
